### ISSUE TITLE
Issue with swift...

### ISSUE THREAD

**Issue by VolceOntra** [NorthernRealities/ColorSenseRainbow#1]
When choosing a color, it is not adding the alpha value thus not adhereing to the UIColor class.  One can get around that by a simple extension like:

extension UIColor{

```
convenience init(red: CGFloat, green:CGFloat, blue:CGFloat) {

    self.init(red: red, green:green, blue:blue, alpha:1.0)
}
```

}

but it would be nice if this was fixed and also giving us an option to control the alpha.

**Comment by NorthernRealities** [comment]
By design if the alpha isn't present in the original then it won't get added when the color is changed, except if you are changing a predefined color.  If you add the alpha then you can change it's value with the picker.  I'm in two minds about how to handle the alpha.  On one side I can put it in automatically.  But with my libraries most of the functions have a default value for the alpha and so it can be left out.

What is the code that you are starting with so that I can test?  

The extension you suggest is a good one and I have it already in my Rainbow-Creator repository.

**Comment by VolceOntra** [comment]
I'm on XCode 6.3.1 and the alpha never gets adjusted if it is there.  I also can't use the plugin if I have the alpha there already.

If it isn't there, it isn't added and XCode states "missing argument for parameter 'alpha' in call"...

I attached a screenshot for you as well.  The color was changed from a UIColor.redColor()

Can't complile:
![screen shot 2015-05-18 at 4 50 53 pm](https://cloud.githubusercontent.com/assets/12501885/7689963/1317c792-fd7e-11e4-9d73-819cbaca3449.png)

Can't choose color:

![screen shot 2015-05-18 at 4 56 17 pm](https://cloud.githubusercontent.com/assets/12501885/7690066/e4472d4e-fd7e-11e4-9ee5-f6f6a37ad72e.png)

**Comment by NorthernRealities** [comment]
Hi.  I've uploaded some fixes that should help out.  When changing the colour from a predefined value (such as redColor() ) then the alpha will always be added.  Also when the alpha isn't present but you change it's value it will be added to the code.  I haven't implemented it yet for colour creation with hexadecimal values using my Rainbow-Creator library.

The reason why the plugin isn't showing up in the second screen shot is because the search criteria are too strict.  It's expecting 1.0 for the alpha and not 1.  I've made a note to go in and loosen up the restrictions.  Looking at it now it would also fail if someone has just entered 0 or 1 for any of the values.

**Comment by VolceOntra** [comment]
Thank you for the quick fix.  I tested out the plugin and it's much better (nice that I don't have to use an extension).  Like you said, it does fail on 0 or 1 however, but that's minor in comparison :+1:

**Comment by NorthernRealities** [comment]
I just put up a patch for the 0 and 1 matching.  I still have to implement the changes for handling the alpha when dealing with colour creating by hexadecimal strings and numbers.  Once that's done I'll roll out a new version number.

Thank you for your feedback. I really appreciate it.

**Comment by NorthernRealities** [comment]
Hi,

I've just put up the patch for the hexadecimal colour creation and rolled out version 1.0 (I'm being optimistic).

Reid.
