### ISSUE TITLE
Only device colors are supported with NSColor

### ISSUE THREAD

**Issue by charlieMonroe** [NorthernRealities/ColorSenseRainbow#10]
On OS X, usually the preferred creation is using the `+colorWithCalibrated*` methods, while this plugin only works with `+colorWithDevice*`. Do you think you could fix this in the next update? Thanks in advance!

**Comment by NorthernRealities** [comment]
Would you be able to provide a bit more detail because I just tried it out on my machine and it was working for colorWithCalibratedRed:

<img width="691" alt="screen shot 2015-08-04 at 15 21 24" src="https://cloud.githubusercontent.com/assets/11425858/9070298/cbf8f724-3abc-11e5-8e4a-1aa4b83f23eb.png">  

I'm pretty sure that this was working before.  I uploaded new code today to support HSB colours and it didn't impact anything to do with the RGB.

It is strange that it would work for the Device and not for the Calibrated because the code is exactly the same.  The only difference between the two is in the regular expression which is can be found in RGBFloatSeeker.swift.  The part of the regular expression looks like 

colorWith(?:Calibrated|Device|SRGB)Red:

If it's still not working for you please send along some examples of working and non-working statements and I'll look further into it.

**Comment by charlieMonroe** [comment]
Sorry about the slightly vague description... I should have mentioned I'm using OS X 10.10.4 with Xcode 7 beta at this moment.

Here is a code snippet (I've indicated which lines it works for and which not):

```
    NSShadow *shadow = [[NSShadow alloc] init];
    [shadow setShadowColor:[NSColor colorWithCalibratedWhite:0.8 alpha:1.0]]; // Doesn't work
    [shadow setShadowBlurRadius:6.0];
    [shadow setShadowOffset:NSMakeSize(3.0, 0.0)];
    [shadow set];

    BOOL b = NO;

    for (x = -30.0;x<r.size.width + 30.0;x+=CMStripesWidth){
        if (b){
            [[NSColor colorWithCalibratedRed:0.255 green:0.471 blue:0.808 alpha:1.0] set]; // Works
        }else{
            [[NSColor blackColor] set]; // Works
        }
        b = !b;
        [NSBezierPath strokeLineFromPoint:NSMakePoint(x - _progressDelta, -10.0) toPoint:NSMakePoint(x-_progressDelta, r.size.height + 10.0)];
    }

    if (_bgAlpha!=0.0){
        shadow = [[NSShadow alloc] init];
        [shadow set];

        [[NSColor colorWithCalibratedWhite:0.0 alpha:_bgAlpha] set]; // Doesn't work, but here the alpha value is a variable
        [[NSBezierPath bezierPathWithRect:r] fill];
    }

    shadow = [[NSShadow alloc] init];
    [shadow setShadowColor:[NSColor colorWithCalibratedWhite:0.8 alpha:1.0]]; // Doesn't work
    [shadow setShadowBlurRadius:6.0];
    [shadow setShadowOffset:NSMakeSize(0.0, 0.0)];
    [shadow set];
```

**Comment by charlieMonroe** [comment]
I'll post more code samples tomorrow.

**Comment by charlieMonroe** [comment]
Ok, I'm sorry about the confusion - after further testing, this issue is only with `[NSColor colorWith(Device|Calibrated)White:0.8 alpha:1.0]`

**Comment by NorthernRealities** [comment]
Hi,

I've just uploaded a new patch which hopefully does everything.  I've never worked with these functions before (or the greyscale colorspace) so my testing was limited to it not crashing Xcode.  I added in support for the functions colorWithWhite for NSColor and UIColor.  For NSColor I also added in colorWith(Device|Calibrated|genericGamma22)White.  And there are the corresponding functions in Swift.  I'd appreciate it if you could test things out and make sure that everything is working.  

Thanks,
Reid.

**Comment by charlieMonroe** [comment]
Thanks, that worked great!

BTW do you think you could also add `AABB7188-E14E-4433-AD3B-5CD791EAD9A3` to the UUIDs array in Info.plist (it's Xcode 7 - I've tested it and seems to be working well).

**Comment by NorthernRealities** [comment]
Hi,

I've added the UUID.  Would you please test it out since I don't have a developer account and can't get Xcode 7 yet?  Just want to make sure that I copied the UUID correctly and that it build OK.

Thanks,
Reid.

**Comment by charlieMonroe** [comment]
Works great, thanks!
