### ISSUE TITLE
Not working in XCode 7

### ISSUE THREAD

**Issue by daniesy** [NorthernRealities/ColorSenseRainbow#14]

**Comment by NorthernRealities** [comment]
Hi,

I don’t know what you mean by not working so I’ll assume that you mean the UUID for Xcode 7 wasn’t recognized.  Another user filed a patch adding the UUID from the Xcode 7 GM and I merged that onto the main branch.

How did you install the plugin?  Do you have the latest code?  I didn’t create a release specifically for the patch which added the UUID so if you are installing via the source code or downloading the plugin directly then you want the latest version from the main branch and not one of the releases.

Reid.

**Comment by Tj3n** [comment]
i also cant get it working in latest xcode 7 that i installed yesterday, i installed it via Alcatraz and restarted

**Comment by NorthernRealities** [comment]
Hi,

I installed 7 on my system today and was able to recreate the issue. For some reason it was complaining about a missing image even though there are none used by the plugin. 

I have to convert the project to Swift 2.0 and see if I can resolve the problem.

**Comment by NorthernRealities** [comment]
Hi,

I uploaded my changes and was able to have the plugin work when installed with Alcatraz.  If someone has a version of Xcode 6 and could test that it still works on there I would be grateful.

Thanks,
Reid.

**Comment by Tj3n** [comment]
thanks, it working now!

**Comment by Bluelich** [comment]
I updated my mac to version of 10.11,it does not work now!
 I  installed it via Alcatraz.
The Xcode version is 7.0.1,and I'v added the UUID of it.

**Comment by NorthernRealities** [comment]
Hi,

Please have a look under the Edit menu in Xcode.  Is there an item labelled “Show Colors Under Carat” at or near the bottom of the list?  If there is then the plugin has been loaded and I’ll have to install 10.11 to see if I can recreate the issue (unless there is no check mark beside the Show in which case you just have to select that menu item to enable the plugin).  

If the menu item doesn’t exist and the plugin hasn’t been loaded would you be able to do the following in order to try and capture some logs for me?
- Quit Xcode
- Open a Terminal and type the following commands
  cd /var/log
  tail -f system.log | grep -i color | grep -v Alcatraz
- It will look like the command is hanging but it’s waiting to read any new lines added to the system.log file
- Start Xcode
- Once Xcode has completed loading return to the Terminal and press Control-c and a prompt will return
- Copy anything that was displayed between “tail -f system.log….” command and the new prompt and send it back to me

Thanks very much,
Reid.

**Comment by hardikdevios** [comment]
Guys this is working with every version just to remind you that you have to write everything in order to display the color just typing a `UIColor`  only and in **_Rgba**_ if you have written only for Red but not fill up other 3 option with alpha then it wont display the Color 
I hope its help you

**Comment by Bluelich** [comment]
Thank you!  It works Now! 
Best wishes to you!

发自我的 iPhone

> 在 2015年10月10日，上午2:36，Reid Gravelle notifications@github.com 写道：
> 
> Hi,
> 
> Please have a look under the Edit menu in Xcode. Is there an item labelled “Show Colors Under Carat” at or near the bottom of the list?  If there is then the plugin has been loaded and I’ll have to install 10.11 to see if I can recreate the issue (unless there is no check mark beside the Show in which case you just have to select that menu item to enable the plugin).  
> 
> If the menu item doesn’t exist and the plugin hasn’t been loaded would you be able to do the following in order to try and capture some logs for me?
> - Quit Xcode
> - Open a Terminal and type the following commands
>   cd /var/log
>   tail -f system.log | grep -i color | grep -v Alcatraz
> - It will look like the command is hanging but it’s waiting to read any new lines added to the system.log file
> - Start Xcode
> - Once Xcode has completed loading return to the Terminal and press Control-c and a prompt will return
> - Copy anything that was displayed between “tail -f system.log….” command and the new prompt and send it back to me
> 
> Thanks very much,
> Reid.
>

**Comment by JulesMoorhouse** [comment]
This didn't work for me :( I tried the system.log thing but nothing was returned.

**Comment by drrost** [comment]
Don't work for Xcode 7.2. Worked well for Xcode 7.1 and 7.1.1

**Comment by NorthernRealities** [comment]
Xcode 7.2 changed the UUID so the plugin needed to be updated which I did yesterday. Please update and see if that solves you issue.

Thanks, 
Reid.

**Comment by drrost** [comment]
It works, thank you.
