### ISSUE TITLE
Xcode 7.1 crashes with the plugin installed

### ISSUE THREAD

**Issue by andr3a88** [NorthernRealities/ColorSenseRainbow#17]
I have this error when i launch xcode 7.1:
**Xcode quit unexpectedly while using the libswiftCore.dylib plug-in.**

**Comment by NorthernRealities** [comment]
How are you installing the plugin?  When I build it from source code it works with Xcode 7.1 on 10.10 and 10.11.  Someone posted a stack trace on Stack Overflow wondering why Xcode was crashing and I was able to see where the cause was.  I've got something but I don't know if it fixes the problem or not and so I'm hesitant to commit my changes. I was wondering if you would be able to test for me since you are experiencing the issue.

Thanks,
Reid.

**Comment by andr3a88** [comment]
At work i installed the plugin building the project from this repo and Xcode always crashes at startup. On my personal computer instead, i try downloading the _ColorSenseRainbow.xcplugin.zip_ and place the plugin in the Plugins directory and it seems to work.  I will check tomorrow at work if it in this way...

**Comment by andr3a88** [comment]
At Work copying _ColorSenseRainbow.xcplugin_ directly to Plugins folder works fine!

**Comment by NorthernRealities** [comment]
That's strange because the plugin was built with the code that's on the main branch.  I'm still looking for someone to test my changes to see if it stops Xcode from crashing before committing them.

**Comment by andr3a88** [comment]
Send me the plugin and I might try it tomorrow

**Comment by NorthernRealities** [comment]
I can't attach .swift files here but the changes are in the file ColorSenseRainbow.swift.  Replace lines 33-37 in the function pluginDidLoad

``` swift
        let appName = NSBundle.mainBundle().infoDictionary?["CFBundleName"] as? NSString
        if appName == "Xcode" {
            dispatch_once( &token ) {
                self.sharedPlugin = ColorSenseRainbow(bundle: bundle)
            }
```

 with the following

``` swift
        if let  infoDict = NSBundle.mainBundle().infoDictionary,
                appNameObj = infoDict[ "CFBundleName" ] {
                    if appNameObj is String {

                        let appName = appNameObj as! NSString
                        if appName == "Xcode" {
                            dispatch_once( &token ) {
                                self.sharedPlugin = ColorSenseRainbow(bundle: bundle)
                            }
                        }

                    }
```

Thanks very much,
Reid.

**Comment by andr3a88** [comment]
I tried with your fix and it works!

**Comment by NorthernRealities** [comment]
Thank you very much for testing.

I've committed my fix and updated the pre-built plugin too so hopefully everything is working properly.

**Comment by andr3a88** [comment]
If you makes other changes in the future, i'm available to test!

**Comment by NorthernRealities** [comment]
Hi Andrea,

I was wondering if you would be able to do me a favour.  I’m just finishing up the next version of the plug-in and was hoping that you might be able to test it out. The big changes for this release are
1. reworking the regular expressions to make them easier to maintain and consistent
2. making the code more readable using some of Swift’s new features
3. using (1) to add support for .init and .f as was requested (for example NSColor.init and 1.f)
4. made it so that when you change the alpha it restricts the number of decimal places to two instead of unlimited
5. added support for a new method I added in my Rainbow-Creator.swift package for creating HSB colours

Everything is under the 1.1.1-working branch.

Thanks very much,
Reid.

**Comment by andr3a88** [comment]
Hi, I will test the branch in these days. Let me know when you push relevant code on this branch so i can update again the plugin!

Andrea

**Comment by NorthernRealities** [comment]
Hi Andrea,

Thanks for helping out.  All of the code is on the branch.

The only thing that I have left to do is to find a way to compile code based on the version of Xcode, if it’s possible. With Xcode 7.3, and Swift 2.2, the method for specifying a selector changed but it isn’t compatible with previous versions. But the old way, the function name in quotes, is deprecated and won’t compile in Swift 3.

Reid.
