### ISSUE TITLE
Problems with alpha: 8.0/255.0

### ISSUE THREAD

**Issue by leo150** [NorthernRealities/ColorSenseRainbow#21]
This line doesn't show color preview:
`UIColor(red: 216.0/255.0, green: 216.0/255.0, blue: 216.0/255.0, alpha: 8.0/255.0)`

**Comment by NorthernRealities** [comment]
Hi,

Yes it won’t because the value part for the alpha isn’t a float between 0 and 1.  The plugin doesn’t support calculated values for the alpha. To be honest I don’t really see what you are trying to do with this example.  I get the red, green, and blue values but not the alpha.

Red, green, and blue (RBG) has been traditionally defined by values between 0 and 255 coming from unsigned 8-bit numbers. For some reason Apple wanted to specify the values for these as floats between 0 and 1 so it’s become traditional for people to take the values and divide by 255.0. Mostly because they are familiar with 216, 216, 216 and not 0.847, 0.847, 0.847. Alpha is the technical name for transparency and goes from 0 to 100% but is entered as a float between 0 and 1.  So in your example you are dividing 8.0 by 255.0 and it doesn’t make sense to me.  Did you want the transparency to be 3% (8/255) or did you want to be 8%.  But since alpha is a percentage people just enter the float value directly as 8/100 is just as readable as 0.08.

If you are interested I do have a repository on GitHub which allows you to write your colour creation as
let backgroundColour = UIColor  ( redValue: 94, greenValue: 7, blueValue: 95, alphaValue: 0.8 )
Though I haven’t seen if it needs to be updated to Swift 2.x but you can find it at https://github.com/NorthernRealities/Rainbow-Creator  If you are happy with the default value of 1.0 for the alpha then you can leave alphaValue off.

Reid.

**Comment by leo150** [comment]
Hi,

Thank you for great response! Yes, it's my fault because I've supposed that alpha's value can be in range of 0..255.
