### ISSUE TITLE
Xcode 7.2.1  the colorBoard not working   How home it ?

### ISSUE THREAD

**Issue by WangGuibin** [NorthernRealities/ColorSenseRainbow#22]
xcode7.2.1 这个颜色板呼不出来了,怎么破?!以前点过去就出来的,前几天还好好的,xcode也没升级也没干嘛,咋就呼不出来了呢....

**Comment by NorthernRealities** [comment]
Hi,

I’m not quite sure what the issue is from your description.  I know that Xcode was recently updated to version 7.3 and that required a new version of the plug-in with a UUID added. To see if you need to update check under the Edit menu. If you don’t see the menu entry “Show Colors Under Carat” at the bottom then the plug-in isn’t being loaded.

Every time that Apple brings out a new release such as 7.0 or 7.3 (but not 7.1.2) they change the UUID of Xcode.  For any plug-ins to work under that release they need to add that UUID to a list of UUIDs.  I try to get a updated version out within a day or two.  However this means that everyone needs to uninstall the old version of the plugin and install the updated version.

Reid

**Comment by WangGuibin** [comment]
Thank you very much ! but I'am not update the Xcode Version7.3 ,it's unstable for reason...
My English is very poor,Don't know how to express, please forgive me. Looking forward to your next version I wish you good luck

**Comment by NorthernRealities** [comment]
Hi,

Another user figured out the problem and I’ve put a fix up yesterday.  

I made a change to get ready for Swift 3 but while Xcode 7.3 supports those changes earlier versions of Xcode have problems with one of them and failed to compile the plug-in. So I removed the changes that caused the problems because everything still works fine under Xcode 7.3, it just causes warnings.

Reid.
