### ISSUE TITLE
Does not seems to work with lastest XCode 7.2.1

### ISSUE THREAD

**Issue by Tj3n** [NorthernRealities/ColorSenseRainbow#23]
Hi, I noticed that this no longer working in my Xcode 7.2.1 in Swift 2.1 project, may u provide support? :D 

I've tried reinstall but also not working

I have UIColor extension and some Lib that alter UIColor (ios-chart), not sure if its the culprit

**Comment by NorthernRealities** [comment]
Hi,

Please check under the Edit menu. If you don’t see the menu entry “Show Colors Under Carat” at the bottom then the plug-in isn’t being loaded. Let me know if it's there or not.

After you determine whether the plug-in is being loaded or not then we can decide how to proceed.  

Thanks,
Reid.

**Comment by Tj3n** [comment]
Hi, It doesn't seems to be there, i think another people also got the same issue but he closed it

**Comment by NorthernRealities** [comment]
Hi,

May you run the following from the command line and send me back the output.  It returns the UUID that Xcode is using and I can see if Apple changed it with the new version.  If they have then I’ll add it and push out a new version of the plug in.

defaults read /Applications/Xcode.app/Contents/Info.plist DVTPlugInCompatibilityUUID

Thanks,
Reid.

**Comment by Tj3n** [comment]
This is the UUID `F41BD31E-2683-44B8-AE7F-5F09E919790E` :D Mine Xcode is 7.2.1

I saw the plist and this also there, now not sure what's causing the culprit

**Comment by NorthernRealities** [comment]
Hi,

Thanks. I just checked and the UUID hasn’t changed with the release of Xcode 7.2.1.  Would you be able to do the following to help me debug?
1. Stop Xcode
2. On the command line enter to following command:
   tail -f /var/log/system.log | grep -i ColorSenseRainbow
3. After Xcode starts press Control-C

Send anything that gets printed to me.

Did you just upgrade to 7.2.1? It came out a couple of months ago.  You mentioned that you have an extension and a library. The plug-in won’t work on those instances because it isn’t configured to recognize those patterns.  Does it work if you create a colour without utilizing those functions?  For example:

let myBlackColor = UIColor.blackColor()

Thanks,
Reid.

**Comment by Tj3n** [comment]
Sorry for the late reply, I think it still work until last month when i upgrade my XCode, Im not admin so i couldn't get the log :(

I don't think its started so of course it doesn't work anywhere, Not sure if its plugins conflict, this is plugins list im using:
- FuzzyAutoComplete
- KSImageNamed
- Realm Plugin
- RegX
- ROTools
- RTImageAssets
- VVDocumenter-Xcode
- Xcode_copy_line

and some themes, all installed by Alcatraz, all working and showing as expected

*Edit: I tried download the source and compile it, then i notice that it have 12 error, probably its the culprit why it doesn't work :D, most of them is because u'r using XCode 7.3, Swift 2.2 `#selector` syntax, hope u can fix it so that it would work for lower version Swift:

![screen shot 2016-04-15 at 12 32 53 pm](https://cloud.githubusercontent.com/assets/13995715/14552231/6292d742-0306-11e6-955e-ba42790e5374.png)

*Edit 2: I changed all `#selector` back to the old `Selector` and compile and now it works :D

**Comment by NorthernRealities** [comment]
Hi,

There is an application under the Utilities directory called Console which lets you view the logs. Maybe you can see them using that.  On the left side there is a panel with a list of the logs. You will want to expand the “/var/log” entry and look for system.log.  The other entries such as system.log.0.gz and system.log.5.gz are from previous days.  

The search field at the top right will look cause a search to be performed in whatever log file you are currently looking at. It won’t search all of the files.  You can search for ColorSenseRainbow and copy any of the text. If you would prefer to send a screenshot of the specific area then it’s Option-Shift-4 and the spacebar toggles between selecting a window to do the screenshot and being able to select a custom area. 

Thanks,
Reid.

**Comment by NorthernRealities** [comment]
Hi,

I thought just occurred to me.  How are you installing the plug-in?  I was wondering if you would try downloading the pre-built version from GitHub and installing that version.  When I built the new version for Xcode 7.3 I made a couple of small changes for deprecated functions and maybe those aren’t supported on 7.2.1. If it’s trying to compile the plug-in and failing due to those changes then it would explain your problems.

It’s just a guess but if you could try it out I would be grateful.

Thanks,
Reid.

**Comment by tj3n123** [comment]
thanks for the reply o. o but u didnt seemy edit? I fiured out its because of the #selector syntax, its only available for swift 2.2 in xcode 7.3

**Comment by NorthernRealities** [comment]
No, sorry, I haven’t seen anything come in.  It’s great that you’ve figured it out.

Reid

**Comment by tj3n123** [comment]
ahhh ic ic :d i changed it to Selector then it can compiled again, i think u can leave it at swift 1 or 2.0 then it fine for most ppl

**Comment by NorthernRealities** [comment]
Hi,

I’ve changed the code and updated it on the main branch.  As I don’t have Xcode 7.2.1 I’d appreciate if you could test it for me.  

I can leave it like that for a short while but those methods are deprecated in Xcode 7.3 which is why I changed them.  They are going to be removed in Swift 3 which is probably going to be in the next version of Xcode.  That’s why I made the change in the first place.  Do you know of a way to compile code based on the  version of Xcode? I found a few things but they were items like the target environment (iOS versus Mac) or the Mac OS version number.  There was the Swift version number which was perfect but it was only introduced in Swift 2.2 which means that anyone compiling the program under Xcode 7.2.1 would have it fail. 

Thanks again for your help,
Reid.

**Comment by Tj3n** [comment]
Thanks, it's working fine now :) Cheers

I'm not sure about compile code based on version of Swift, I think u can do a check for [XCode's max iOS version (__IPHONE_OS_VERSION_MAX_ALLOWED)](http://stackoverflow.com/questions/29140476/how-can-i-programmatically-find-swifts-version), hope it helps!

**Comment by NorthernRealities** [comment]
Hi,

I was wondering if you would be able to do me a favour.  I’m just finishing up the next version of the plug-in and was hoping that you might be able to test it out.  I’ve left the selector statements alone for the moment. The big changes for this release are
1. reworking the regular expressions to make them easier to maintain and consistent
2. making the code more readable using some of Swift’s new features
3. using (1) to add support for .init and .f as was requested (for example NSColor.init and 1.f)
4. made it so that when you change the alpha it restricts the number of decimal places to two instead of unlimited
5. added support for a new method I added in my Rainbow-Creator.swift package for creating HSB colours

Thanks very much,
Reid.

**Comment by NorthernRealities** [comment]
Hi,

Sorry, I forgot to mention that everything is under the 1.1.1-working branch.

Reid.

**Comment by Tj3n** [comment]
Hi, I tried it and seems to work fine, except that it have a `#selector` in ColorSenseRainbow.swift, I figured out that if people don't update their OSX to El Capital, the max version of XCode they can use is 7.2.1 eg. Swift 2, so maybe u can just keep it working till that version of Swift :)

I have tried it in Swift  and Obj-C proj, all working fine
Worked with 1.f
Worked with changing HSB slider
Worked with .init
Alpha only have 2 decimal number

Great plugin, Cheers :D

**Comment by NorthernRealities** [comment]
Thanks for testing. I changed the #selector that I missed. 

My next task is to find out if it’s possible to have the old and new way in the code and it compiles based on the version of Xcode. I’m not making the change for the fun of it. In Swift 3, which I’m guessing will be announced in a couple of months at WWDC, the old way is being removed and it won’t compile anymore.  Right now it just generates a deprecated warning in Xcode 7.3. 

Thanks again for your help,
Reid.

**Comment by Tj3n** [comment]
Glad to help, I think starting from Swift 2.2 only have convenience function to check for Swift version, hope the SO answer above can help. :D I have updated my OSX and XCode now so it would work fine
