### ISSUE TITLE
Can it support color macros?

### ISSUE THREAD

**Issue by heramerom** [NorthernRealities/ColorSenseRainbow#7]
Can it support color macros, like "UIColor3B(r, g, b)","__RGB(r, g, b)", "UIHexColor(hex)" etc..

**Comment by NorthernRealities** [comment]
Hi,

Yes it can support them.  Basically the plugin is just a text searcher.  There are details on how to extend the functionality on the main page for the plugin at the bottom of the Readme.  As long as you can create a regular expression and get values to generate a colour from it then there would be a problem.  From the examples you give there wouldn’t be a problem.  

Because the plugin is run every time the carat is moved I put in an optimization in the file ColorFinder.swift which looks for the string Color in the current line.  If it isn’t found then the seekers, which execute regular expressions, aren’t called.  If you wanted to expand the functionality to include macros such as __RGB then this optimization would have to be taken out.

Are these your own macros?  I looked for UIHexColor and couldn’t find anything.  I have an extension to UIColor and NSColor that adds functionality such as creating colours with RGB integer values between 0 and 255, hex strings and ints, and CGFloats but without the alpha which it defaults to 1.0.  These are already supported in the plugin.  The extension is called Rainbow Creator and can be found at https://github.com/NorthernRealities/Rainbow-Creator

Reid.

**Comment by heramerom** [comment]
Thank you.

**Comment by heramerom** [comment]
Yes, I defined the UIHexColor macros. like this 

```
#define UIHex4Color(rgbaValue)  [UIColor colorWithRed:((float)((rgbValue & 0xFF000000) >> 24))/255.0 green:((float)((rgbValue & 0xFF0000) >> 16))/255.0 blue:((float)(rgbValue & 0xFF00) >> 8)/255.0 alpha:((float)(rgbValue & 0xFF))/255.0]
```
