### ISSUE TITLE
more expand?

### ISSUE THREAD

**Issue by SoulArsenic** [NorthernRealities/ColorSenseRainbow#8]
method that `colorWithHue:saturation:brightness:alpha:` could be support?

**Comment by NorthernRealities** [comment]
Hi,

Yes this can be done.  I explain how to do this in the Readme file.  Or were you asking me to do this?

Reid.

**Comment by SoulArsenic** [comment]
I did not notice that. will try later by mySelf, THX

**Comment by NorthernRealities** [comment]
Hi,

I had some time and just uploaded code that should support colours that are created with HSB in Swift and Objective-C.  Would you be able to test it for me and let me know if it's working properly?  I gave it a quick go on my system and it seems okay but since I've never worked with HSB before I'd like to make sure before I create a new version.

I was wondering if you knew of or would be interested in an extension in Swift that would allow you to create the colours by specifying the values as integers instead of converting everything as a value between 0 and 1.  For example: newColour = UIColor ( hue: 270 saturation: 87 brightness: 100 alpha: 1.0 ).  I just noticed that a lot of places on the web specified colours in degrees and percent but the functions wanted a CGFloat.  I created a similar function for RGB values in my Rainbow Creator repository.  It was just an idea that if you thought useful I could put on my list of things to do.

**Comment by SoulArsenic** [comment]
`UIColor ( hue: rvalue saturation: gvalue brightness: bvalue alpha: avalue(0-1) )` also works for me .

I think it would bee a useful function.
